import { blogPosts } from "@/content/blog";
import { productVideos } from "@/content/videos";
import { catalog, catalogCategories, deals, featuredProducts } from "@/content/catalog";
import { navItems } from "@/content/nav";
import { pageCopy } from "@/content/page-copy";
import {
  PRICE,
  RING_PRICE,
  SHARE_PRICE,
  STRAP_PRICE,
  GLASSES_PRICE,
  BUDS_PRICE,
  WATCH_PRICE,
  announcement,
  appScreens,
  bandFeatures,
  bandVariants,
  batteryFacts,
  boxFacts,
  budsFacts,
  budsFaqs,
  budsFeatures,
  calculatorDefaultMonthly,
  careNotes,
  company,
  dayStory,
  developmentNotice,
  faqs,
  footerBlurb,
  footerMarketplaces,
  storeLinks,
  glassesFacts,
  glassesFaqs,
  glassesFeatures,
  headerSlogan,
  helpArticles,
  inTheBox,
  noSubscription,
  paymentMethods,
  policies,
  priceLabel,
  ringFacts,
  ringFaqs,
  ringFeatures,
  ringPriceLabel,
  ringSizes,
  ringVariants,
  shareBuds,
  shareFacts,
  sharePriceLabel,
  siteDescription,
  SITE_URL,
  socialLinks,
  specs,
  strapPriceLabel,
  support,
  supportMenu,
  trustItems,
  useSteps,
  watchFacts,
  watchFaqs,
  watchFeatures,
  watchPriceLabel,
  watchVariants,
  budsPriceLabel,
  glassesPriceLabel,
} from "@/content/site";
import type { ContentBundle } from "@/lib/content/types";

export function staticBundle(): ContentBundle {
  return {
    siteUrl: SITE_URL,
    market: { code: "US", name: "United States", currency: "USD" },
    markets: [{ code: "US", name: "United States", currency: "USD" }],
    logo: { url: "/brand/joova-wordmark-color.png", width: 917, height: 191 },
    company,
    policies,
    announcement,
    notices: {
      development: { text: developmentNotice, enabled: true, color: "red", background: "ink" },
      shipping: { text: announcement, enabled: true, color: "white", background: "ink" },
    },
    headerSlogan,
    footerBlurb,
    footerMarketplaces,
    storeLinks: storeLinks.map((store) => ({ ...store })),
    siteDescription,
    noSubscription,
    supportMenu: [...supportMenu],
    navItems: navItems.map((item) => ({ ...item })),
    support: {
      email: support.email,
      promise: support.promise,
      channels: support.channels.map((channel) => ({ ...channel })),
    },
    catalog: catalog.map((product) => ({ ...product, alsoIn: product.alsoIn ? [...product.alsoIn] : undefined })),
    catalogCategories: catalogCategories.map((category) => ({ ...category })),
    deals: deals.map((deal) => ({ ...deal, compareAtLabel: null, image: null })),
    featuredProducts: [...featuredProducts],
    socialLinks: socialLinks.map((link) => ({ ...link })),
    paymentMethods: paymentMethods.map((method) => ({ ...method })),
    blogPosts: blogPosts.map((post) => ({
      ...post,
      points: [...post.points],
      sections: post.sections.map((section) => ({ ...section, paragraphs: [...section.paragraphs] })),
    })),
    productVideos: [...productVideos],
    helpArticles: helpArticles.map((article) => ({ ...article })),
    bandVariants: [...bandVariants],
    ringVariants: [...ringVariants],
    watchVariants: [...watchVariants],
    prices: {
      band: PRICE,
      ring: RING_PRICE,
      share: SHARE_PRICE,
      straps: STRAP_PRICE,
      glasses: GLASSES_PRICE,
      buds: BUDS_PRICE,
      watch: WATCH_PRICE,
    },
    priceLabels: {
      band: priceLabel,
      ring: ringPriceLabel,
      share: sharePriceLabel,
      straps: strapPriceLabel,
      glasses: glassesPriceLabel,
      buds: budsPriceLabel,
      watch: watchPriceLabel,
    },
    faqs: [...faqs],
    specs: [...specs],
    bandFeatures: [...bandFeatures],
    ringFeatures: [...ringFeatures],
    ringFacts: [...ringFacts],
    ringFaqs: [...ringFaqs],
    watchFeatures: [...watchFeatures],
    watchFacts: [...watchFacts],
    watchFaqs: [...watchFaqs],
    glassesFeatures: [...glassesFeatures],
    glassesFacts: [...glassesFacts],
    glassesFaqs: [...glassesFaqs],
    budsFeatures: [...budsFeatures],
    budsFacts: [...budsFacts],
    budsFaqs: [...budsFaqs],
    shareBuds: [...shareBuds],
    shareFacts: [...shareFacts],
    dayStory: [...dayStory],
    appScreens: [...appScreens],
    trustItems: [...trustItems],
    inTheBox: [...inTheBox],
    useSteps: [...useSteps],
    careNotes: [...careNotes],
    boxFacts: [...boxFacts],
    batteryFacts: [...batteryFacts],
    ringSizes: [...ringSizes],
    calculatorDefaultMonthly,
    pageCopy: {
      about: { ...pageCopy.about },
      privacy: { ...pageCopy.privacy },
      terms: { ...pageCopy.terms },
      accessibility: { ...pageCopy.accessibility },
      returns: { ...pageCopy.returns },
      warranty: { ...pageCopy.warranty },
    },
  };
}

export const blockIds = [
  "faqs",
  "specs",
  "bandFeatures",
  "ringFeatures",
  "ringFacts",
  "ringFaqs",
  "watchFeatures",
  "watchFacts",
  "watchFaqs",
  "glassesFeatures",
  "glassesFacts",
  "glassesFaqs",
  "budsFeatures",
  "budsFacts",
  "budsFaqs",
  "shareBuds",
  "shareFacts",
  "dayStory",
  "appScreens",
  "trustItems",
  "inTheBox",
  "useSteps",
  "careNotes",
  "boxFacts",
  "batteryFacts",
] as const;
