export type CountryOption = {
  code: string;
  name: string;
  currency: string;
};

const rows: [string, string, string][] = [
  ["AF", "Afghanistan", "AFN"],
  ["AL", "Albania", "ALL"],
  ["DZ", "Algeria", "DZD"],
  ["AS", "American Samoa", "USD"],
  ["AD", "Andorra", "EUR"],
  ["AO", "Angola", "AOA"],
  ["AI", "Anguilla", "XCD"],
  ["AG", "Antigua and Barbuda", "XCD"],
  ["AR", "Argentina", "ARS"],
  ["AM", "Armenia", "AMD"],
  ["AW", "Aruba", "AWG"],
  ["AU", "Australia", "AUD"],
  ["AT", "Austria", "EUR"],
  ["AZ", "Azerbaijan", "AZN"],
  ["BS", "Bahamas", "BSD"],
  ["BH", "Bahrain", "BHD"],
  ["BD", "Bangladesh", "BDT"],
  ["BB", "Barbados", "BBD"],
  ["BY", "Belarus", "BYN"],
  ["BE", "Belgium", "EUR"],
  ["BZ", "Belize", "BZD"],
  ["BJ", "Benin", "XOF"],
  ["BM", "Bermuda", "BMD"],
  ["BT", "Bhutan", "BTN"],
  ["BO", "Bolivia", "BOB"],
  ["BA", "Bosnia and Herzegovina", "BAM"],
  ["BW", "Botswana", "BWP"],
  ["BR", "Brazil", "BRL"],
  ["BN", "Brunei", "BND"],
  ["BG", "Bulgaria", "BGN"],
  ["BF", "Burkina Faso", "XOF"],
  ["BI", "Burundi", "BIF"],
  ["KH", "Cambodia", "KHR"],
  ["CM", "Cameroon", "XAF"],
  ["CA", "Canada", "CAD"],
  ["CV", "Cape Verde", "CVE"],
  ["KY", "Cayman Islands", "KYD"],
  ["CF", "Central African Republic", "XAF"],
  ["TD", "Chad", "XAF"],
  ["CL", "Chile", "CLP"],
  ["CN", "China", "CNY"],
  ["CO", "Colombia", "COP"],
  ["KM", "Comoros", "KMF"],
  ["CG", "Congo", "XAF"],
  ["CD", "Congo, Democratic Republic", "CDF"],
  ["CK", "Cook Islands", "NZD"],
  ["CR", "Costa Rica", "CRC"],
  ["CI", "Côte d’Ivoire", "XOF"],
  ["HR", "Croatia", "EUR"],
  ["CU", "Cuba", "CUP"],
  ["CW", "Curaçao", "ANG"],
  ["CY", "Cyprus", "EUR"],
  ["CZ", "Czechia", "CZK"],
  ["DK", "Denmark", "DKK"],
  ["DJ", "Djibouti", "DJF"],
  ["DM", "Dominica", "XCD"],
  ["DO", "Dominican Republic", "DOP"],
  ["EC", "Ecuador", "USD"],
  ["EG", "Egypt", "EGP"],
  ["SV", "El Salvador", "USD"],
  ["GQ", "Equatorial Guinea", "XAF"],
  ["ER", "Eritrea", "ERN"],
  ["EE", "Estonia", "EUR"],
  ["SZ", "Eswatini", "SZL"],
  ["ET", "Ethiopia", "ETB"],
  ["FK", "Falkland Islands", "FKP"],
  ["FO", "Faroe Islands", "DKK"],
  ["FJ", "Fiji", "FJD"],
  ["FI", "Finland", "EUR"],
  ["FR", "France", "EUR"],
  ["GF", "French Guiana", "EUR"],
  ["PF", "French Polynesia", "XPF"],
  ["GA", "Gabon", "XAF"],
  ["GM", "Gambia", "GMD"],
  ["GE", "Georgia", "GEL"],
  ["DE", "Germany", "EUR"],
  ["GH", "Ghana", "GHS"],
  ["GI", "Gibraltar", "GIP"],
  ["GR", "Greece", "EUR"],
  ["GL", "Greenland", "DKK"],
  ["GD", "Grenada", "XCD"],
  ["GP", "Guadeloupe", "EUR"],
  ["GU", "Guam", "USD"],
  ["GT", "Guatemala", "GTQ"],
  ["GG", "Guernsey", "GBP"],
  ["GN", "Guinea", "GNF"],
  ["GW", "Guinea-Bissau", "XOF"],
  ["GY", "Guyana", "GYD"],
  ["HT", "Haiti", "HTG"],
  ["HN", "Honduras", "HNL"],
  ["HK", "Hong Kong", "HKD"],
  ["HU", "Hungary", "HUF"],
  ["IS", "Iceland", "ISK"],
  ["IN", "India", "INR"],
  ["ID", "Indonesia", "IDR"],
  ["IR", "Iran", "IRR"],
  ["IQ", "Iraq", "IQD"],
  ["IE", "Ireland", "EUR"],
  ["IM", "Isle of Man", "GBP"],
  ["IL", "Israel", "ILS"],
  ["IT", "Italy", "EUR"],
  ["JM", "Jamaica", "JMD"],
  ["JP", "Japan", "JPY"],
  ["JE", "Jersey", "GBP"],
  ["JO", "Jordan", "JOD"],
  ["KZ", "Kazakhstan", "KZT"],
  ["KE", "Kenya", "KES"],
  ["KI", "Kiribati", "AUD"],
  ["XK", "Kosovo", "EUR"],
  ["KW", "Kuwait", "KWD"],
  ["KG", "Kyrgyzstan", "KGS"],
  ["LA", "Laos", "LAK"],
  ["LV", "Latvia", "EUR"],
  ["LB", "Lebanon", "LBP"],
  ["LS", "Lesotho", "LSL"],
  ["LR", "Liberia", "LRD"],
  ["LY", "Libya", "LYD"],
  ["LI", "Liechtenstein", "CHF"],
  ["LT", "Lithuania", "EUR"],
  ["LU", "Luxembourg", "EUR"],
  ["MO", "Macao", "MOP"],
  ["MG", "Madagascar", "MGA"],
  ["MW", "Malawi", "MWK"],
  ["MY", "Malaysia", "MYR"],
  ["MV", "Maldives", "MVR"],
  ["ML", "Mali", "XOF"],
  ["MT", "Malta", "EUR"],
  ["MH", "Marshall Islands", "USD"],
  ["MQ", "Martinique", "EUR"],
  ["MR", "Mauritania", "MRU"],
  ["MU", "Mauritius", "MUR"],
  ["YT", "Mayotte", "EUR"],
  ["MX", "Mexico", "MXN"],
  ["FM", "Micronesia", "USD"],
  ["MD", "Moldova", "MDL"],
  ["MC", "Monaco", "EUR"],
  ["MN", "Mongolia", "MNT"],
  ["ME", "Montenegro", "EUR"],
  ["MS", "Montserrat", "XCD"],
  ["MA", "Morocco", "MAD"],
  ["MZ", "Mozambique", "MZN"],
  ["MM", "Myanmar", "MMK"],
  ["NA", "Namibia", "NAD"],
  ["NR", "Nauru", "AUD"],
  ["NP", "Nepal", "NPR"],
  ["NL", "Netherlands", "EUR"],
  ["NC", "New Caledonia", "XPF"],
  ["NZ", "New Zealand", "NZD"],
  ["NI", "Nicaragua", "NIO"],
  ["NE", "Niger", "XOF"],
  ["NG", "Nigeria", "NGN"],
  ["NU", "Niue", "NZD"],
  ["MK", "North Macedonia", "MKD"],
  ["NO", "Norway", "NOK"],
  ["OM", "Oman", "OMR"],
  ["PK", "Pakistan", "PKR"],
  ["PW", "Palau", "USD"],
  ["PS", "Palestine", "ILS"],
  ["PA", "Panama", "PAB"],
  ["PG", "Papua New Guinea", "PGK"],
  ["PY", "Paraguay", "PYG"],
  ["PE", "Peru", "PEN"],
  ["PH", "Philippines", "PHP"],
  ["PL", "Poland", "PLN"],
  ["PT", "Portugal", "EUR"],
  ["PR", "Puerto Rico", "USD"],
  ["QA", "Qatar", "QAR"],
  ["RE", "Réunion", "EUR"],
  ["RO", "Romania", "RON"],
  ["RU", "Russia", "RUB"],
  ["RW", "Rwanda", "RWF"],
  ["BL", "Saint Barthélemy", "EUR"],
  ["KN", "Saint Kitts and Nevis", "XCD"],
  ["LC", "Saint Lucia", "XCD"],
  ["MF", "Saint Martin", "EUR"],
  ["VC", "Saint Vincent and the Grenadines", "XCD"],
  ["WS", "Samoa", "WST"],
  ["SM", "San Marino", "EUR"],
  ["ST", "São Tomé and Príncipe", "STN"],
  ["SA", "Saudi Arabia", "SAR"],
  ["SN", "Senegal", "XOF"],
  ["RS", "Serbia", "RSD"],
  ["SC", "Seychelles", "SCR"],
  ["SL", "Sierra Leone", "SLE"],
  ["SG", "Singapore", "SGD"],
  ["SX", "Sint Maarten", "ANG"],
  ["SK", "Slovakia", "EUR"],
  ["SI", "Slovenia", "EUR"],
  ["SB", "Solomon Islands", "SBD"],
  ["SO", "Somalia", "SOS"],
  ["ZA", "South Africa", "ZAR"],
  ["KR", "South Korea", "KRW"],
  ["SS", "South Sudan", "SSP"],
  ["ES", "Spain", "EUR"],
  ["LK", "Sri Lanka", "LKR"],
  ["SD", "Sudan", "SDG"],
  ["SR", "Suriname", "SRD"],
  ["SE", "Sweden", "SEK"],
  ["CH", "Switzerland", "CHF"],
  ["SY", "Syria", "SYP"],
  ["TW", "Taiwan", "TWD"],
  ["TJ", "Tajikistan", "TJS"],
  ["TZ", "Tanzania", "TZS"],
  ["TH", "Thailand", "THB"],
  ["TL", "Timor-Leste", "USD"],
  ["TG", "Togo", "XOF"],
  ["TO", "Tonga", "TOP"],
  ["TT", "Trinidad and Tobago", "TTD"],
  ["TN", "Tunisia", "TND"],
  ["TR", "Turkey", "TRY"],
  ["TM", "Turkmenistan", "TMT"],
  ["TC", "Turks and Caicos Islands", "USD"],
  ["TV", "Tuvalu", "AUD"],
  ["UG", "Uganda", "UGX"],
  ["UA", "Ukraine", "UAH"],
  ["AE", "United Arab Emirates", "AED"],
  ["GB", "United Kingdom", "GBP"],
  ["US", "United States", "USD"],
  ["UY", "Uruguay", "UYU"],
  ["UZ", "Uzbekistan", "UZS"],
  ["VU", "Vanuatu", "VUV"],
  ["VA", "Vatican City", "EUR"],
  ["VE", "Venezuela", "VES"],
  ["VN", "Vietnam", "VND"],
  ["VG", "Virgin Islands, British", "USD"],
  ["VI", "Virgin Islands, U.S.", "USD"],
  ["YE", "Yemen", "YER"],
  ["ZM", "Zambia", "ZMW"],
  ["ZW", "Zimbabwe", "USD"],
];

export const countries: CountryOption[] = rows.map(([code, name, currency]) => ({ code, name, currency }));

const byCode = new Map(countries.map((country) => [country.code, country]));

export function countryByCode(code: string) {
  return byCode.get(code.toUpperCase()) ?? null;
}

export const unitedStates = countryByCode("US")!;
